chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('cours/', views.cours, name='cours'),
    path('compte/', views.compte_view, name='compte'),
    path('parametre/', views.parametre_view, name='parametre'),
    path('cours/<str:cours_name>/', views.chatbot, name='chatbot'),
    path('logout/', views.user_logout, name='logout'),    
    path('new_chat/', views.new_chat, name='new_chat'),
    path('load/<str:session_id>', views.load_chats, name='load'),
    path('delete/<str:session_id>', views.delete_session, name='delete_session'),
    path('delete_all_sessions', views.delete_all_sessions, name='delete_all_sessions'),
    path('get_chatbot_response/', views.get_chatbot_response, name='get_chatbot_response'),
    path('info/', views.info, name='info'),

    ]

django_chatbot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls'))
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    telephone = models.CharField(max_length=20)
    date_naissance = models.DateField(null=True, blank=True)
    genre = models.CharField(max_length=10, choices=[('M', 'Masculin'), ('F', 'Féminin')])
    niveau = models.CharField(max_length=10, choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème')])
    ville = models.CharField(max_length=100)

    def __str__(self):
        return f"Profil de {self.user.username}"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Session(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    title = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='session')
    created = models.DateTimeField(auto_now_add=True)
    cours_name = models.TextField(default='cours name')

    def __str__(self):
        return f"Session {self.title}"

class Chat(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    created = models.DateTimeField(auto_now_add=True)
    session = models.ForeignKey(Session, on_delete=models.CASCADE, related_name='chats', blank=True, null=True)
    message = models.TextField()
    response = models.TextField()

    def __str__(self):
        return self.message

chat/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import JsonResponse
import uuid
import markdown
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from chat.models import Chat, Session
from response import generate_response, make_title

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.views.decorators.csrf import csrf_protect
from django.db import transaction
from django.contrib import messages
from .models import UserProfile




@csrf_protect
def home(request):
    if request.user.is_authenticated:
        return redirect('cours')
    
    if request.method == 'POST':
        form_type = request.POST.get('form_type')
        if form_type == 'login':
            return handle_login(request)
        elif form_type == 'register':
            return handle_register(request)
    
    return render(request, 'home.html')

def handle_login(request):
    email = request.POST.get('email')
    password = request.POST.get('password')

    user = authenticate(request, username=email, password=password)
    if user is not None:
        login(request, user)
        return redirect('cours')
    else:
        return render(request, 'home.html', {'login_error': 'Email ou mot de passe incorrect'})

@transaction.atomic
def handle_register(request):
    nom = request.POST.get('nom')
    prenom = request.POST.get('prenom')
    email = request.POST.get('email')
    telephone = request.POST.get('telephone')
    date_naissance = request.POST.get('date_naissance')
    genre = request.POST.get('genre')
    niveau = request.POST.get('niveau')
    ville = request.POST.get('ville')
    password = request.POST.get('password')

    # Validation de base
    if not all([nom, prenom, email, telephone, date_naissance, genre, niveau, ville, password]):
        return render(request, 'home.html', {'register_error': 'Tous les champs sont requis'})

    try:
        validate_email(email)
    except ValidationError:
        return render(request, 'home.html', {'register_error': 'Email invalide'})

    if User.objects.filter(email=email).exists():
        return render(request, 'home.html', {'register_error': 'Cet email est déjà utilisé'})

    # Création de l'utilisateur
    try:
        user = User.objects.create_user(
            username=email,
            email=email,
            password=password,
            first_name=prenom,
            last_name=nom
        )

        # Mise à jour du profil utilisateur
        user.profile.telephone = telephone
        user.profile.date_naissance = date_naissance
        user.profile.genre = genre
        user.profile.niveau = niveau
        user.profile.ville = ville
        user.profile.save()

        login(request, user)
        return redirect('cours')
    except Exception as e:
        return render(request, 'home.html', {'register_error': f"Erreur lors de l'inscription: {str(e)}"})

@login_required
def user_logout(request):
    logout(request)
    return redirect('home')


def generate_uuid():
    return str(uuid.uuid4())

def save_chat(request, session_id, message, response):
    session = get_object_or_404(Session, id=session_id)
    session.title =make_title(message)
    session.save()
    chat = Chat.objects.create(
        session=session,
        message=message,
        response=response
    )
    
@login_required(login_url='home')
def cours(request):
    return render(request, 'cours.html')

@login_required(login_url='home')
def compte_view(request):
    return render(request, 'compte.html')

@login_required(login_url='home')
def parametre_view(request):
    return render(request, 'parametre.html')

    return generate_response(message)

@login_required(login_url='home')
def chatbot(request, cours_name):
    new_session = Session(
            cours_name = cours_name,
            title='Nouvelle discussion',
            user=request.user,
        )
    new_session.save()
    context = {
        'cours_name': cours_name, 
        'sessions' :Session.objects.filter(user=request.user, cours_name=cours_name).order_by('-created')[:5], 
        'new_session':new_session}

    return render(request, 'chat.html', context)


def get_chatbot_response(request):
    if request.method == 'POST':
        user_message = request.POST.get('message')
        session_id = request.POST.get('session_id')
        cours_name = request.POST.get('cours_name')
        classe = request.POST.get('classe')
      
        chatbot_response = generate_response(user_message, session_id, cours_name, classe)
        save_chat(request, session_id, user_message, chatbot_response)
        
        chatbot_response = markdown.markdown(chatbot_response, extensions=['markdown.extensions.fenced_code'])
        return JsonResponse({'response': chatbot_response})


chats = []
@login_required(login_url='home')
def load_chats(request, session_id):
    cours_name = request.GET.get('cours_name')
    session = get_object_or_404(Session, id=session_id)
    user_chats = Chat.objects.filter(session=session)
    for chat in user_chats:
        chats.append(chat)

    context = {
        'chats': user_chats, 
        'cours_name': cours_name,
        'new_session': session, 
        'sessions' :Session.objects.filter(user=request.user, cours_name=cours_name).order_by('-created')[:5]}
    
    return render(request, 'chat.html', context, )



@login_required(login_url='home')
def delete_session(request, session_id):
    cours_name = {'cours_name': request.GET.get('cours_name')}
    session  = Session.objects.get(id=session_id)
    session.delete()
    return redirect('cours')

@login_required(login_url='home')
def new_chat(request):
    cours_name = request.GET.get('cours_name')
    new_session = Session(
            cours_name = cours_name,
            title='Nouvelle discussion',
            user=request.user,
        )
    new_session.save()
    context = {
        'cours_name': cours_name, 
        'sessions' :Session.objects.filter(user=request.user, cours_name=cours_name).order_by('-created')[:5], 
        'new_session':new_session}

    return render(request, 'chat.html', context)


@login_required(login_url='home')
def delete_all_sessions(request):
    # Supprime toutes les sessions, ce qui supprimera également tous les chats associés
    Session.objects.all().delete()
    return redirect('cours') 


@login_required
def info(request):
    if request.method == 'POST':
        user = request.user
        profile = user.profile

        # Mise à jour des champs de l'utilisateur
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        # L'e-mail n'est plus mis à jour
        user.save()

        # Mise à jour des champs du profil
        profile.telephone = request.POST.get('telephone')
        profile.date_naissance = request.POST.get('date_naissance')
        # Le niveau n'est plus mis à jour
        profile.ville = request.POST.get('ville')
        profile.save()

        messages.success(request, 'Vos informations ont été mises à jour avec succès.')
        return redirect('compte')

    return render(request, 'compte.html', {
        'user': request.user,
        'profile': request.user.profile
    })


def process_file(request):
    if request.method == 'POST' and request.FILES.get('file'):
        uploaded_file = request.FILES['file']
        # A venir
        # Lire le contenu du fichier
        

chat/templates/chat.html
{% load static %}
{% load chat_extra %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'images/chat-bot.svg' %}" type="image/x-icon"/>
    <title>Cours</title>
    <!-- Liens vers les polices et feuilles de style -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.css">
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">
    <link rel="stylesheet" href="{% static 'css/loader.css' %}">
    <link rel="stylesheet" href="{% static 'css/bubble.css' %}">
    <link rel="stylesheet" href="{% static 'css/list_cours.css' %}">
</head>
<body>
    <div class="accueil">
        <!-- Menu latéral -->
        <aside class="menu-1">
            <!-- Logo -->
            <a href="{% url 'cours' %}">
                <div class="logo-1">
                    <img src="{% static 'images/Logo.svg' %}" alt="logo">
                </div>
            </a>
            <!-- Navigation principale -->
            <nav>
                <ul>
                    <li><a href="{% url 'cours' %}"><img src="{% static 'vectors/dashbord_1.svg' %}" alt="Tableau de bord">Tableau de bord</a></li>
                    <li class="active"><img src="{% static 'vectors/cours_1.svg' %}" alt="Cours">Cours</li>
                    <li><a href="{% url 'compte' %}"><img src="{% static 'vectors/compte.svg' %}" alt="Mon compte">Mon compte</a></li>
                    <li><a href="{% url 'parametre' %}"><img src="{% static 'vectors/parametre.svg' %}" alt="Paramètres">Paramètres</a></li>
                </ul>
            </nav>
            
            <!-- Pied de page du menu latéral -->
            <div class="footer">
                <div class="help">
                    <img src="{% static 'vectors/help.svg' %}" alt="Aide">
                    <span><a href="https://wa.me/22677534419">Besoin d'aide</a></span>
                </div>
                <button class="subscription" onclick="location.href=''">Changer d'abonnement</button>
                <div class="logout">
                    <img src="{% static 'vectors/logout.svg' %}" alt="Déconnexion">
                    <span><a href="{% url 'logout' %}">Se déconnecter</a></span>
                </div>
            </div>
        </aside>

        <!-- Contenu principal -->
        <main class="cours">
            <!-- En-tête du cours -->
            <header class="cours-header">
                <!-- Informations du cours -->
                <div class="cours-container">
                    <div class="cours-info">
                        <img src="/static/vectors/cours.svg" alt="Cours">
                        <span>Cours : {{cours_name|upper}} {{user.profile.niveau}}</span>
                        <button class="plus-button">
                            <img src="{% static 'vectors/plus.svg' %}" alt="Plus">
                        </button>
                    </div>
                </div>
                <!-- Menu des discussions -->
                <div class="discussions nav">
                    <li>
                        <span class="num">{{ sessions|length }}</span>
                        <button class="discussions-button">
                            <img src="{% static 'vectors/discussion.svg' %}" alt="Discussions">
                        </button>
                        
                        <ul>
                            <!--  -->
                            <li class="title">Mes discussions 
                                <a href="{% url 'new_chat' %}?cours_name={{ cours_name }}">
                                    <button class="add-btn">
                                        <i class="fa fa-plus" aria-hidden="true"></i> Nouvelle discussion
                                    </button>
                                </a> 
                                <a href="{% url 'delete_all_sessions' %}">
                                    <button class="delete-btn">
                                        <i class="fa fa-trash" aria-hidden="true"></i> Tout supprimer
                                    </button>
                                </a>
                            </li>
                            
                            {% for session in sessions %}
                                <li>
                                    <a href="{% url 'load' session.id %}?cours_name={{ cours_name }}">{{ session.title }} | {{ session.created }}</a>
                                    <a href="{% url 'delete_session' session.id %}?cours_name={{ cours_name }}"> <button class="delete-btn"><i class="fa fa-trash" aria-hidden="true"></i></button></a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <span style="margin-right: 30px;">Historiques</span>
                </div>
                
                <!-- Profil de l'utilisateur -->
                <div class="profile">
                    <a href="{% url 'compte' %}">
                      <div>
                        <img class="profile-pic" src="https://avatar.iran.liara.run/username?username={{user.first_name}}+{{user.last_name}}"/>
                      </div>
                    </a>
                    <div class="profile-info">
                      <div class="name">
                          <span>{{ user.first_name }}</span>
                      </div>
                      <div class="grade">{{ user.profile.niveau }}</div>
                    </div>
                  </div>
            </header>
            <ul class="cours-liste" id="coursList">
                <li><a href="{% url 'chatbot' 'maths' %}">MATHS 3eme</a></li>
                <li><a href="{% url 'chatbot' 'physique-chimie' %}">PC 3eme</a></li>
                <li><a href="{% url 'chatbot' 'français' %}">FRANCAIS 3eme</a></li>
                <li><a href="{% url 'chatbot' 'anglais' %}">ANGLAIS 3eme</a></li>
                <li><a href="{% url 'chatbot' 'svt' %}">SVT 3eme</a></li>
                <li><a href="{% url 'chatbot' 'histoire-geographie' %}">HG 3eme</a></li>
            </ul>
            
            <!-- Zone de chat -->
            <ul id="chat" class="chat-thread">
                {% for chat in chats %}
                    <!-- Message de l'utilisateur -->
                    <li class="user-message">
                        {{ chat.message }}
                    </li>
                    <!-- Message du chatbot -->
                    <li class="bot-message">
                        <div class="bot-avatar">
                            <img src="{% static 'images/chat-bot.svg' %}" alt="Bot Image" class="bot-image">
                        </div>
                        {{ chat.response|convert_markdown|safe}}
                    </li>
                {% endfor %}
            </ul>
            
            <!-- Zone de saisie -->
           
            <div class="chat-container">
                <div class="suggestion" id="file-info" style="display: none;">
                    <div class="suggestion-item">
                        <button class="suggestion-icon" id="remove-file">
                            <img src="{% static 'vectors/close.svg' %}" alt="Remove File">
                        </button>
                        <span class="suggestion-text">
                            <img id="file-icon" src="" alt="File Icon" style="width: 20px; height: 20px; margin-right: 5px; vertical-align: middle;">
                            <span id="file-name"></span>
                        </span>
                    </div>
                </div>
                <div class="chat-bottom">
                    <form id="form" class="chat-form" action="" method="post">
                        {% csrf_token %}
                        <div class="input-container">
                            <div class="input-wrapper">
                                <input type="file" id="file-input" style="display: none;" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png">
                                <button class="upload-button" type="button" onclick="document.getElementById('file-input').click();">
                                    <img src="{% static 'vectors/add.svg' %}" alt="Upload">
                                </button>
                                <textarea rows='1' id="message" type="text" required placeholder="Que voudrais-tu savoir aujourd'hui ?"></textarea>
                                <input type="hidden" id="session_id" value="{{ new_session.id }}"></input>
                            </div>
                            <div class="button-wrapper">
                                <button class="mic-button" type="button">
                                    <img src="{% static 'vectors/mic.svg' %}" class="mic-icon">
                                </button>
                                <button class="send-button" type="submit">
                                    <img src="{% static 'vectors/send.svg' %}" alt="Envoyer">
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
    </div>
    
    <!-- Scripts JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/2.0.3/marked.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.2.3/howler.min.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/contrib/auto-render.min.js"></script>
    <script src="{% static 'js/chat.js' %}"></script>
    <script src="{% static 'js/info.js' %}"></script>
    <script src="{% static 'js/list_cours.js' %}"></script>
    <script>
        const image = "{% static 'images/image.png' %}";
        const pdf = "{% static 'images/pdf.png' %}";
        const doc = "{% static 'images/doc.png' %}";
        const files = "{% static 'images/file.png' %}";
        const MIC_ICON = "{% static 'vectors/mic.svg' %}";
        const MIC_ACTIVE_ICON = "{% static 'vectors/mic-active.svg' %}";
    </script>
    <script src="{% static 'js/voice-recognition.js' %}"></script>
    <script src="{% static 'js/load.js' %}"></script>
    <script src="{% static 'js/reponse_bubble.js' %}"></script>
    {% comment %} <script src="{% static 'js/remove_link.js' %}"></script> {% endcomment %}

</body>
</html>

chat/templates/compte.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'images/chat-bot.svg' %}" type="image/x-icon"/>
    <title>Compte</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/compte.css' %}">
    <link rel="stylesheet" href="{% static 'css/loader.css' %}">
</head>
<body>
    <div class="accueil">
        <aside class="menu-1">
            <a href="{% url 'cours' %}">
              <div class="logo-1">
                  <img src="{% static 'images/Logo.svg' %}" alt="logo">
              </div>
           </a>
            <nav>
              <ul>
                  <li >
                    <a href="{% url 'cours' %}">
                      <img src="{% static 'vectors/dashbord_1.svg' %}" alt="Tableau de bord icon">
                      <span>Tableau de bord</span>
                    </a>
                  </li>
                  <li >
                    <a href="{% url 'chatbot' 'maths' %}">
                      <img src="{% static 'vectors/cours.svg' %}" alt="Cours icon">
                      <span>Cours</span>
                    </a>
                  </li>
                  <li class="active">
                      <a href="{% url 'compte' %}">
                        <img src="{% static 'vectors/compte_1.svg' %}" alt="Mon compte icon">
                        <span>Mon compte</span>
                      </a>
                  </li>
                  <li>
                    <a href="{% url 'parametre' %}">
                      <img src="{% static 'vectors/parametre.svg' %}" alt="Paramètres icon">
                      <span>Paramètres</span>
                    </a>
                  </li>
              </ul>
          </nav>
          <div class="footer">
              <div class="help">
                  <img src="{% static 'vectors/help.svg' %}" alt="Aide icon">
                  <span><a href="https://wa.me/22677534419">Besoin d'aide</a></span>
              </div>
              <button class="subscription" onclick="location.href=''">Changer d'abonnement</button>
              <div class="logout">
                  <img src="{% static 'vectors/logout.svg' %}" alt="Déconnexion icon">
                  <span><a href="{% url 'logout' %}">Se déconnecter</a></span>
              </div>
          </div>
        </aside>
        <main class="tableau-de-bord">
            <header>
                <div class="search-bar">
                    <input type="text" placeholder="Rechercher les matières">
                    <img src="{% static 'vectors/search.svg' %}" alt="Search icon">
                </div>
                <div class="profile">
                  <a href="{% url 'compte' %}">
                    <div>
                      <img class="profile-pic" src="https://avatar.iran.liara.run/username?username={{user.first_name}}+{{user.last_name}}"/>
                    </div>
                  </a>
                  <div class="profile-info">
                    <div class="name">
                        <span>{{ user.first_name }}</span>
                    </div>
                    <div class="grade">{{ user.profile.niveau }}</div>
                  </div>
                </div>
            </header>
            <h2>Informations personnelles</h2>
            <form method="post" action="{% url 'info' %}">
              {% csrf_token %}
              <div class="profile-container">
                <div class="profil-compte-container">
                  <img class="profil-compte" src="https://avatar.iran.liara.run/username?username={{user.first_name}}+{{user.last_name}}" alt="Photo de profil">
                </div>
                <div class="details">
                  <div class="item">
                    <div class="label">Numéro de téléphone</div>
                    <div class="value">
                      <input type="tel" name="telephone" value="{{ user.profile.telephone }}">
                    </div>
                  </div>
                  <div class="item">
                    <div class="label">Adresse mail</div>
                    <div class="value">
                      <input type="email" value="{{ user.email }}" readonly class="readonly-field">
                    </div>
                  </div>
                  <div class="item">
                    <div class="label">Nom</div>
                    <div class="value">
                      <input type="text" name="last_name" value="{{ user.last_name }}">
                    </div>
                  </div>
                  <div class="item">
                    <div class="label">Prénom(s)</div>
                    <div class="value">
                      <input type="text" name="first_name" value="{{ user.first_name }}">
                    </div>
                  </div>
                  <div class="item">
                    <div class="label">Date de naissance</div>
                    <div class="value">
                      <input type="date" name="date_naissance" value="{{ user.profile.date_naissance|date:'Y-m-d' }}">
                    </div>
                  </div>
                  <div class="item">
                    <div class="label">Niveau</div>
                    <div class="value">
                      <input type="text" value="{{ user.profile.get_niveau_display }}" readonly class="readonly-field">
                    </div>
                  </div>
                  <div class="item">
                    <div class="label">Ville</div>
                    <div class="value">
                      <input type="text" name="ville" value="{{ user.profile.ville }}">
                    </div>
                  </div>
                </div>
              </div>
              <div class="save-container">
                  <button type="submit" class="save">
                      <img src="{% static 'vectors/save.svg' %}" alt="Save icon">
                      <span class="save-text">Enregistrer les modifications</span>
                  </button>
              </div>
          </form>
        </main>
    </div>
    <script src="{% static 'js/load.js' %}"></script>
</body>
</html>